### ISSUE TITLE
Due to Unity Mod Manager load order, Tabletop Tweaks overrides Scaling Cantrips.

### ISSUE THREAD

**Issue by Amariithynar** [RealityMachina/Scaling-Cantrips#2]
I really like this mod, but I also really like Tabletop Tweaks, as well. Due to the mod load order in Unity Mod Manager being just "sort by alphabetical", and mods with a lower load order taking priority, unfortunately the changes from Scaling Cantrips gets overwritten by Tabletop Tweaks; is there any way that this can be resolved so that it doesn't override without needing to change internal ID information in the mod with each update?

**Comment by RealityMachina** [comment]
Can I get a explanation of what Tabletop Tweaks overrides, specifically? I also use tabletop tweaks and have had it installed when testing so I imagine it's a specific thing that's causing conflicts that I missed.

**Comment by Amariithynar** [comment]
> Can I get a explanation of what Tabletop Tweaks overrides, specifically? I also use tabletop tweaks and have had it installed when testing so I imagine it's a specific thing that's causing conflicts that I missed.

Er, for me, it's everything. None of the cantrip tooltips update, none of their mechanics change, and none of the new cantrips appear at all, either. I have to go into the info.json and rename everything to something that goes below Tabletop Tweaks to get it to work at all with it installed (I'd have just renamed it to "RealityMachina's Scaling Cantrips" if that would have worked, but as is I'm just being super lazy and naming it TScaling Cantrips because that works well enough with minimal effort XD). I selectively disabled Tabletop Tweaks before (and reloaded the game to ensure a fresh mod load atop the game) and it worked then, but never when it was activated.

**Comment by RealityMachina** [comment]
That is...confusing then.

Are you using a particular version of Unity Mod Manager? I'm trying to think of reasons a conflict could exist without me finding it on my end...

**Comment by Amariithynar** [comment]
0.23.4, and updates since have only been regarding adding some other games, so I doubt it matters... It could be related to the version of the mod I was using, perhaps? I was using 1.4 and it also had a bug with the display and functionality of the Unholy Zap cantrip which I reported in a separate issue, where (other issues aside) it was dealing 1d3 damage not 1d as the tooltip stated; updating to 1.4.1, which you released a while after I made these posts, resolved that. Let me see if 1.4.1 also lets me ignore mod order..... And yeah! 1.4.1 does seem to work fine. Guess it was a specific version weirdness issue? I've not changed anything other than the version of the mod I'm using now.

**Comment by Amariithynar** [comment]
0.23.4, and updates since have only been regarding adding some other games, so I doubt it matters... It could be related to the version of the mod I was using, perhaps? I was using 1.4 and it also had a bug with the display and functionality of the Unholy Zap cantrip which I reported in a separate issue, where (other issues aside) it was dealing 1d3 damage not 1d6 as the tooltip stated; updating to 1.4.1, which you released a while after I made these posts, resolved that. Let me see if 1.4.1 also lets me ignore mod order..... And yeah! 1.4.1 does seem to work fine. Guess it was a specific version weirdness issue? I've not changed anything other than the version of the mod I'm using now. Going to update to 1.4.4 since I see that you implemented the change from Disrupt Undead as the base concept to Divine Zap, which was the majority of why that post was made, hah.

**Comment by Amariithynar** [comment]
Seems to work fine with 1.4.4 now too, so yeah, guess it was just some oddity with 1.4? On a related note, the scaling is set to every three levels and max out at 4d3 for Unholy Zap. That's not within the purview of this issue, though. Closing.
