### ISSUE TITLE
Startup problem with 1.5.8.

### ISSUE THREAD

**Issue by patrikucarlsson** [RealityMachina/Scaling-Cantrips#20]
Using this mod with Pathfinder WOTR and get stucked. It causes the game to be stuck at the startup screen when the game starts. WOTR is version 2.4.0x and Scaling cantrips is version 1.5.8. Other mods works.

**Comment by RealityMachina** [comment]
Thank you for reporting this!

**Comment by patrikucarlsson** [comment]
Many Thanks for the update!
