### ISSUE TITLE
Firebolt not adding to the Thassilonian Specialist cantrip sets by default.

### ISSUE THREAD

**Issue by Amariithynar** [RealityMachina/Scaling-Cantrips#6]
Exactly as it says on the tin. At least, doesn't work for Gluttony.

**Comment by RealityMachina** [comment]
Fixed in 1.5.2

**Comment by Amariithynar** [comment]
> Fixed in 1.5.2

Er, you only added it to the evocation type, not all of them, though? XD

**Comment by Amariithynar** [comment]
There we go, fixed in 1.5.5. :D
