### ISSUE TITLE
Cantrip expert on all feat lists

### ISSUE THREAD

**Issue by mjones1052** [RealityMachina/Scaling-Cantrips#7]
I looked but didn't see anything that I recall, but cantrip expert feat shows up for everyone, regardless whether they can cast spells, is that normal? Figured being able to cast spells would be a prerequisite.

**Comment by Amariithynar** [comment]
Agreed; I think that the line "ability to cast level 1 divine spells/ability to cast level 1 arcane spells" is the most reasonable to use for that.

**Comment by mjones1052** [comment]
think this was fixed!
