### ISSUE TITLE
New update broke it?

### ISSUE THREAD

**Issue by mjones1052** [RealityMachina/Scaling-Cantrips#9]
Seems like the 9/29 update broke it?

**Comment by dhavard** [comment]
Still seems to work for me. What about it is broken for you?

**Comment by mjones1052** [comment]
As a wizard I have no cantrips. My oracle doesn't either. My cleric does however which is weird. So it seems to be hit or miss. It happened with the update before the update where they fixed auto casting cantrips.

**Comment by RealityMachina** [comment]
Cantrips should re-add themselves if missing with the latest update, upon a character levelling up (so respecing a character should proc it as well)
